# Generated by Django 5.0.4 on 2024-05-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder_size', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.TextField(max_length=200)),
            ],
        ),
    ]
