# Generated by Django 3.2.23 on 2024-05-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gasapp', '0002_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder_size', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.TextField(max_length=200)),
                ('total_amount', models.CharField(max_length=20)),
            ],
        ),
    ]
