# Generated by Django 5.0.4 on 2024-05-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gasapp', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
